### ISSUE TITLE
Issue with the editProductState

### ISSUE THREAD

**Issue by nfaith** [423s22/G4#23]
![editProductState Issue](https://user-images.githubusercontent.com/49287441/165839487-31822d1d-a243-4ea4-833a-83bc9ddf0fb9.JPG)

# Issue when attempting to edit a product.

* Error was reproduced every time when done on the users' device
* No code was significantly changed
* Seems to be an issue with the _updateSaveStatus() feature, being applied onRender. This is due to the innerHTML being set to NULL in that function.

**Comment by CodeAX2** [comment]
Fixed on the branch with the issue
